### ISSUE TITLE
Tests failed in Ubuntu

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse-paho/paho.mqtt.c#273]
Run you build script (as wrote in travis-build.sh) without SSL
```
mkdir build.paho
cd build.paho
echo "travis build dir $TRAVIS_BUILD_DIR pwd $PWD"
cmake -DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE ..
make
python ../test/mqttsas2.py &
ctest -VV --timeout 600
kill %1 %2
```

```
travis build dir  pwd /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- CMake version: 2.8.12.2
-- CMake system name: Linux
-- Timestamp is Wed May  3 19:17:46 UTC 2017
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho
Scanning dependencies of target common_obj
[  2%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolClient.c.o
[  5%] Building C object src/CMakeFiles/common_obj.dir/Clients.c.o
[  8%] Building C object src/CMakeFiles/common_obj.dir/utf-8.c.o
[ 11%] Building C object src/CMakeFiles/common_obj.dir/StackTrace.c.o
[ 14%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacket.c.o
[ 17%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacketOut.c.o
[ 20%] Building C object src/CMakeFiles/common_obj.dir/Messages.c.o
[ 22%] Building C object src/CMakeFiles/common_obj.dir/Tree.c.o
[ 25%] Building C object src/CMakeFiles/common_obj.dir/Socket.c.o
[ 28%] Building C object src/CMakeFiles/common_obj.dir/Log.c.o
[ 31%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistence.c.o
[ 34%] Building C object src/CMakeFiles/common_obj.dir/Thread.c.o
[ 37%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolOut.c.o
[ 40%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistenceDefault.c.o
[ 42%] Building C object src/CMakeFiles/common_obj.dir/SocketBuffer.c.o
[ 45%] Building C object src/CMakeFiles/common_obj.dir/Heap.c.o
[ 48%] Building C object src/CMakeFiles/common_obj.dir/LinkedList.c.o
[ 48%] Built target common_obj
Scanning dependencies of target paho-mqtt3a
[ 51%] Building C object src/CMakeFiles/paho-mqtt3a.dir/MQTTAsync.c.o
Linking C shared library libpaho-mqtt3a.so
[ 51%] Built target paho-mqtt3a
Scanning dependencies of target paho-mqtt3c
[ 54%] Building C object src/CMakeFiles/paho-mqtt3c.dir/MQTTClient.c.o
Linking C shared library libpaho-mqtt3c.so
[ 54%] Built target paho-mqtt3c
Scanning dependencies of target MQTTVersion
[ 57%] Building C object src/CMakeFiles/MQTTVersion.dir/MQTTVersion.c.o
Linking C executable MQTTVersion
[ 57%] Built target MQTTVersion
Scanning dependencies of target MQTTAsync_publish
[ 60%] Building C object src/samples/CMakeFiles/MQTTAsync_publish.dir/MQTTAsync_publish.c.o
Linking C executable MQTTAsync_publish
[ 60%] Built target MQTTAsync_publish
Scanning dependencies of target MQTTAsync_subscribe
[ 62%] Building C object src/samples/CMakeFiles/MQTTAsync_subscribe.dir/MQTTAsync_subscribe.c.o
Linking C executable MQTTAsync_subscribe
[ 62%] Built target MQTTAsync_subscribe
Scanning dependencies of target MQTTClient_publish
[ 65%] Building C object src/samples/CMakeFiles/MQTTClient_publish.dir/MQTTClient_publish.c.o
Linking C executable MQTTClient_publish
[ 65%] Built target MQTTClient_publish
Scanning dependencies of target MQTTClient_publish_async
[ 68%] Building C object src/samples/CMakeFiles/MQTTClient_publish_async.dir/MQTTClient_publish_async.c.o
Linking C executable MQTTClient_publish_async
[ 68%] Built target MQTTClient_publish_async
Scanning dependencies of target MQTTClient_subscribe
[ 71%] Building C object src/samples/CMakeFiles/MQTTClient_subscribe.dir/MQTTClient_subscribe.c.o
Linking C executable MQTTClient_subscribe
[ 71%] Built target MQTTClient_subscribe
Scanning dependencies of target paho_c_pub
[ 74%] Building C object src/samples/CMakeFiles/paho_c_pub.dir/paho_c_pub.c.o
Linking C executable paho_c_pub
[ 74%] Built target paho_c_pub
Scanning dependencies of target paho_c_sub
[ 77%] Building C object src/samples/CMakeFiles/paho_c_sub.dir/paho_c_sub.c.o
Linking C executable paho_c_sub
[ 77%] Built target paho_c_sub
Scanning dependencies of target paho_cs_pub
[ 80%] Building C object src/samples/CMakeFiles/paho_cs_pub.dir/paho_cs_pub.c.o
Linking C executable paho_cs_pub
[ 80%] Built target paho_cs_pub
Scanning dependencies of target paho_cs_sub
[ 82%] Building C object src/samples/CMakeFiles/paho_cs_sub.dir/paho_cs_sub.c.o
Linking C executable paho_cs_sub
[ 82%] Built target paho_cs_sub
Scanning dependencies of target test1
[ 85%] Building C object test/CMakeFiles/test1.dir/test1.c.o
Linking C executable test1
[ 85%] Built target test1
Scanning dependencies of target test2
[ 88%] Building C object test/CMakeFiles/test2.dir/test2.c.o
Linking C executable test2
[ 88%] Built target test2
Scanning dependencies of target test4
[ 91%] Building C object test/CMakeFiles/test4.dir/test4.c.o
Linking C executable test4
[ 91%] Built target test4
Scanning dependencies of target test6
[ 94%] Building C object test/CMakeFiles/test6.dir/test6.c.o
Linking C executable test6
[ 94%] Built target test6
Scanning dependencies of target test8
[ 97%] Building C object test/CMakeFiles/test8.dir/test8.c.o
Linking C executable test8
[ 97%] Built target test8
Scanning dependencies of target test9
[100%] Building C object test/CMakeFiles/test9.dir/test9.c.o
Linking C executable test9
[100%] Built target test9

Listening on port 1884, broker on port 1883
UpdateCTestConfiguration  from :/home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/DartConfiguration.tcl
Test project /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: test1-1-single-thread-client

1: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test1 "--test_no" "1" "--connection" "tcp://localhost:1883"
1: Test timeout computed to be: 540
1: 
1: Setting connection to tcp://localhost:1883
1: 20170503 121536.619 Starting test 1 - single threaded client using receive
1: =========================================================
1:                    Trace Output
1: Product name: Paho Synchronous MQTT C Client Library
1: Version: 1.1.0
1: Build level: Wed May  3 19:15:32 UTC 2017
1: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
1: 
1: =========================================================
1: 20170503 121536.620 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test1.c, line 396, description: Good rc from connect
1: 
1: rc was -120170503 121536.620 TEST1: test failed. 2 tests run, 1 failures.
1: 20170503 121536.620 verdict fail
 1/25 Test  #1: test1-1-single-thread-client .............................***Failed    0.00 sec
test 2
      Start  2: test1-2-multithread-callbacks

2: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test1 "--test_no" "2" "--connection" "tcp://localhost:1883"
2: Test timeout computed to be: 540
2: 
2: Setting connection to tcp://localhost:1883
2: 20170503 121536.623 Starting test 2 - multi-threaded client using callbacks
2: =========================================================
2:                    Trace Output
2: Product name: Paho Synchronous MQTT C Client Library
2: Version: 1.1.0
2: Build level: Wed May  3 19:15:32 UTC 2017
2: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
2: 
2: =========================================================
2: 20170503 121536.853 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test1.c, line 559, description: Good rc from connect
2: 
2: rc was -120170503 121536.853 failed: test test2. 2 tests run, 1 failures.
2: 20170503 121536.853 verdict fail
 2/25 Test  #2: test1-2-multithread-callbacks ............................***Failed    0.23 sec
test 3
      Start  3: test1-3-connack-return-codes

3: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test1 "--test_no" "3" "--connection" "tcp://localhost:1883"
3: Test timeout computed to be: 540
3: 
3: Setting connection to tcp://localhost:1883
3: 20170503 121536.855 Starting test 3 - connack return codes
3: =========================================================
3:                    Trace Output
3: Product name: Paho Synchronous MQTT C Client Library
3: Version: 1.1.0
3: Build level: Wed May  3 19:15:32 UTC 2017
3: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
3: 
3: =========================================================
3: 20170503 121536.856 passed: test test3. 1 tests run, 0 failures.
3: 20170503 121536.856 verdict pass
 3/25 Test  #3: test1-3-connack-return-codes .............................   Passed    0.00 sec
test 4
      Start  4: test1-4-client-persistence

4: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test1 "--test_no" "4" "--connection" "tcp://localhost:1883"
4: Test timeout computed to be: 540
4: 
4: Setting connection to tcp://localhost:1883
4: 20170503 121536.857 Starting test 4 - persistence, qos 1
4: =========================================================
4:                    Trace Output
4: Product name: Paho Synchronous MQTT C Client Library
4: Version: 1.1.0
4: Build level: Wed May  3 19:15:32 UTC 2017
4: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
4: 
4: =========================================================
4: 20170503 121536.858 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test1.c, line 707, description: Good rc from connect
4: 
4: rc was -120170503 121536.858 Starting test 4 - persistence, qos 2
4: 20170503 121536.858 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test1.c, line 707, description: Good rc from connect
4: 
4: rc was -120170503 121536.858 verdict fail
 4/25 Test  #4: test1-4-client-persistence ...............................***Failed    0.00 sec
test 5
      Start  5: test1-5-disconnect-with-quiesce

5: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test1 "--test_no" "5" "--connection" "tcp://localhost:1883"
5: Test timeout computed to be: 540
5: 
5: Setting connection to tcp://localhost:1883
5: 20170503 121536.860 Starting test 5 - disconnect with quiesce timeout should allow exchanges to complete
5: =========================================================
5:                    Trace Output
5: Product name: Paho Synchronous MQTT C Client Library
5: Version: 1.1.0
5: Build level: Wed May  3 19:15:32 UTC 2017
5: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
5: 
5: =========================================================
5: 20170503 121536.861 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test1.c, line 872, description: Good rc from connect
5: 
5: rc was -120170503 121536.861 failed: test test 5. 1 tests run, 1 failures.
5: 20170503 121536.861 verdict fail
 5/25 Test  #5: test1-5-disconnect-with-quiesce ..........................***Failed    0.00 sec
test 6
      Start  6: test1-6-connlost-will-message

6: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test1 "--test_no" "6" "--connection" "tcp://localhost:1883" "--proxy_connection" "tcp://localhost:1884"
6: Test timeout computed to be: 540
6: 
6: Setting connection to tcp://localhost:1883
6: 20170503 121536.862 Starting test 6 - connectionLost and will messages
6: =========================================================
6:                    Trace Output
6: Product name: Paho Synchronous MQTT C Client Library
6: Version: 1.1.0
6: Build level: Wed May  3 19:15:32 UTC 2017
6: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
6: 
6: =========================================================
(None, None, None) True
Traceback (most recent call last):
  File "../test/mqttsas2.py", line 47, in handle
    brokers.connect((brokerhost, brokerport))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
6: 20170503 121536.985 waitfor unexpectedly is NULL for client Client_1, packet_type 2, timeout 29888
6: 20170503 121536.986 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test1.c, line 983, description: good rc from connect
6: 
6: rc was -1
6: 20170503 121536.986 failed: test test6. 3 tests run, 1 failures.
6: 
6: 20170503 121536.986 verdict fail
 6/25 Test  #6: test1-6-connlost-will-message ............................***Failed    0.13 sec
test 7
      Start  7: test2-1-multiple-threads-single-client

7: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test2 "--connection" "tcp://localhost:1883"
7: Test timeout computed to be: 540
7: 
7: Setting connection to tcp://localhost:1883
7: 20170503 121536.990 Starting test 1 - multiple threads using same client object
7: =========================================================
7:                    Trace Output
7: Product name: Paho Synchronous MQTT C Client Library
7: Version: 1.1.0
7: Build level: Wed May  3 19:15:32 UTC 2017
7: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
7: 
7: =========================================================
7: 20170503 121537.212 Assertion failed, file /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/test/test2.c, line 444, description: Good rc from connect
7: 
7: rc was -120170503 121537.212 TEST1: test failed. 3 tests run, 1 failures.
7: 20170503 121537.212 verdict fail
 7/25 Test  #7: test2-1-multiple-threads-single-client ...................***Failed    0.22 sec
test 8
      Start  8: test4-1-basic-connect-subscribe-receive

8: Test command: /home/dontsov/adapters2/adp_ext_var/tmp/env-build/linux64_gcc/master.zip/master.zip/paho.mqtt.c-master/build.paho/test/test4 "--test_no" "1" "--connection" "tcp://localhost:1883"
8: Test timeout computed to be: 540
8: 20170503 121537.213 Product name: Paho Asynchronous MQTT C Client Library
8: 20170503 121537.214 Version: 1.1.0
8: 20170503 121537.214 Build level: Wed May  3 19:15:32 UTC 2017
8: 20170503 121537.214 Starting test 1 - asynchronous connect
```

**Comment by icraggs** [comment]
These run successfully on Travis for every push.  (https://travis-ci.org/eclipse/paho.mqtt.c/branches)

Have you actually installed and run Mosquitto with the configuration file in the project, as shown in the travis-install.sh file?  All the information you need is in the project.

**Comment by icraggs** [comment]
I'm assuming running Mosquitto will fix this.

**Comment by dontsovcmc** [comment]
Sorry for answer delay. You are right! 
I'm start Mosquitto and previous tests had been passed.

Some tests used openssl failed.
For example:

32: Test command: /home/dontsov/Downloads/paho.mqtt.c-master/build.paho/test/test5 "--test_no" "7" "--hostname" "localhost" "--client_key" "/test/ssl/client.pem" "--server_key" "/test/ssl/test-root-ca.crt"
32: Test timeout computed to be: 540
32: Setting connection to ssl://localhost:18883
32: Setting mutual_auth_connection to ssl://localhost:18884
32: Setting nocert_mutual_auth_connection to ssl://localhost:18887
32: Setting server_auth_connection to ssl://localhost:18885
32: Setting anon_connection to ssl://localhost:18886
32: 20170505 070726.910 Starting test 4 - accept invalid server certificates
32: =========================================================
32:                    Trace Output
32: Product name: Paho Asynchronous MQTT C Client Library
32: Version: 1.1.0
32: Build level: Fri May  5 14:05:45 UTC 2017
32: OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
32: OpenSSL flags: compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
32: OpenSSL build timestamp: built on: Mon Feb 29 18:11:15 UTC 2016
32: OpenSSL platform: platform: debian-amd64
32: OpenSSL directory: OPENSSLDIR: "/usr/lib/ssl"
32: /proc/version: Linux version 3.13.0-83-generic (buildd@lgw01-55) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
32: 
32: =========================================================
32: Assertion failed, file /home/dontsov/Downloads/paho.mqtt.c-master/test/test5.c, line 1201, description: There should be no failures in this test. test4OnConnectFailure callback was called
32: 20170505 070727.218 failed: test test4. 3 tests run, 1 failures.
32: 20170505 070727.218 Total tests run: 3
32: 20170505 070727.218 verdict fail
32/42 Test #32: test5-4-accept-invalid-certificates ...............................***Failed    0.31 sec

**Comment by icraggs** [comment]
Did you start Mosquitto with the supplied TLS configuration as shown in travis-install.sh?

mosquitto -c test/tls-testing/mosquitto.conf &

**Comment by dontsovcmc** [comment]
You are also right :D.
I try to start with you conf, but got error:
Error: Unknown configuration variable "cafile".
Error: Unable to open configuration file.
