### ISSUE TITLE
MQTTClient_publishMessage hangs for about 20 seconds [CLIENT_VERSION  "1.0.3"]

### ISSUE THREAD

**Issue by kamilgucwa** [eclipse-paho/paho.mqtt.c#296]
MQTTClient.c
#define BUILD_TIMESTAMP "Mon Feb 16 11:01:58 CET 2015"
#define CLIENT_VERSION  "1.0.3"

MQTT_TRACE_LEVEL=MAXIMUM
```
20170705 191115.515 (1662473696) (0)< MQTTClient_publishMessage:1516 (0)
20170705 191115.515 (1662473696) (0)> MQTTClient_isConnected:1203
20170705 191115.515 (1662473696) (0)< MQTTClient_isConnected:1208 (1)
**20170705 191115.515** (1662473696) (0)> MQTTClient_publishMessage:1500
**20170705 191136.823** (1662473696)  (1)> MQTTClient_publish:1410
20170705 191136.823 (1662473696)   (2)> UTF8_validateString:155
20170705 191136.823 (1662473696)    (3)> UTF8_validate:129
20170705 191136.823 (1662473696)     (4)> UTF8_char_validate:79
20170705 191136.823 (1662473696)     (4)< UTF8_char_validate:113
                                         // 70 x sequence of UTF8_char_validate  omitted for convenience // (1+70+1 equals the length of message topic, 72 chars)
20170705 191136.825 (1662473696)     (4)> UTF8_char_validate:79
20170705 191136.825 (1662473696)     (4)< UTF8_char_validate:113
20170705 191136.825 (1662473696)    (3)< UTF8_validate:141 (1)
20170705 191136.825 (1662473696)   (2)< UTF8_validateString:157 (1)
20170705 191136.825 (1662473696)   (2)> MQTTProtocol_assignMsgId:74
20170705 191136.825 (1662473696)   (2)< MQTTProtocol_assignMsgId:87 (125)
20170705 191136.825 Allocating 48 bytes in heap at file src/MQTTClient.c line 1448 ptr 0x8e0750
20170705 191136.825 (1662473696)   (2)> MQTTProtocol_startPublish:147
20170705 191136.825 Allocating 48 bytes in heap at file src/MQTTProtocolClient.c line 173 ptr 0x8e07f0
20170705 191136.825 (1662473696)    (3)> MQTTProtocol_createMessage:175
20170705 191136.825 Allocating 32 bytes in heap at file src/MQTTProtocolClient.c line 208 ptr 0x8e3d90
20170705 191136.825 (1662473696)     (4)> MQTTProtocol_storePublication:210
20170705 191136.825 Allocating 80 bytes in heap at file src/MQTTProtocolClient.c line 218 ptr 0x8e06f0
20170705 191136.825 Allocating 295280 bytes in heap at file src/MQTTProtocolClient.c line 225 ptr 0x939f20
20170705 191136.825 Allocating 32 bytes in heap at file src/LinkedList.c line 93 ptr 0x89d530
20170705 191136.826 (1662473696)     (4)< MQTTProtocol_storePublication:230
20170705 191136.826 (1662473696)    (3)< MQTTProtocol_createMessage:195
20170705 191136.826 Allocating 32 bytes in heap at file src/LinkedList.c line 93 ptr 0x995830
20170705 191136.826 (1662473696)    (3)> MQTTProtocol_startPublishCommon:124
20170705 191136.826 (1662473696)     (4)> MQTTPacket_send_publish:678
20170705 191136.826 Allocating 16 bytes in heap at file src/MQTTPacket.c line 679 ptr 0x8e3dc0
20170705 191136.826 Allocating 16 bytes in heap at file src/MQTTPacket.c line 687 ptr 0x8f0a60
20170705 191136.826 (1662473696)      (5)> MQTTPacket_sends:227
20170705 191136.826 Allocating 16 bytes in heap at file src/MQTTPacket.c line 228 ptr 0x8e3e80
20170705 191136.826 (1662473696)       (6)> MQTTPacket_encode:269
20170705 191136.826 (1662473696)       (6)< MQTTPacket_encode:279 (3)
20170705 191136.826 (1662473696)       (6)> MQTTPersistence_put:347
20170705 191136.826 (1662473696)       (6)< MQTTPersistence_put:381 (0)
20170705 191136.826 (1662473696)       (6)> SSLSocket_putdatas:732
20170705 191136.826 Allocating 295360 bytes in heap at file src/SSLSocket.c line 737 ptr 0xb37fa0
20170705 191136.826 Freeing 295360 bytes in heap at file src/SSLSocket.c line 772, heap use now 593712 bytes
20170705 191136.826 (1662473696)       (6)< SSLSocket_putdatas:783 (0)
20170705 191136.826 Freeing 16 bytes in heap at file src/MQTTPacket.c line 253, heap use now 298352 bytes
20170705 191136.826 (1662473696)      (5)< MQTTPacket_sends:254 (0)
20170705 191136.826 Freeing 16 bytes in heap at file src/MQTTPacket.c line 698, heap use now 298336 bytes
20170705 191136.828 Freeing 16 bytes in heap at file src/MQTTPacket.c line 711, heap use now 298320 bytes
20170705 191136.828 15 connector_isservice_mqtt_writer_online@s037alisa474 -> PUBLISH msgid: 125 qos: 1 retained: 0 (0) payload: 31a4406b-60d6-4400-b
20170705 191136.828 (1662473696)     (4)< MQTTPacket_send_publish:717 (0)
20170705 191136.828 (1662473696)    (3)< MQTTProtocol_startPublishCommon:128 (0)
20170705 191136.828 (1662473696)   (2)< MQTTProtocol_startPublish:158 (0)
20170705 191136.828 Freeing 48 bytes in heap at file src/MQTTClient.c line 1476, heap use now 298304 bytes
20170705 191136.828 (1662473696)  (1)< MQTTClient_publish:1489 (0)
20170705 191136.828 (1662473696) (0)< MQTTClient_publishMessage:1516 (0)
20170705 191136.828 (1662473696) (0)> MQTTClient_waitForCompletion:1847
```
We are using Paho C 1.0.3 within our C++ application under SLES 12, the message broker is HiveMQ located physically on the same machine. 
It has happened on the production, that Paho C hanged for about 20 seconds during MQTTClient_publishMessage. 
What the cause could be? There is really not much to do between MQTTClient_publishMessage and MQTTClient_publish

**Comment by icraggs** [comment]
No, there is not much to do.  I can think of two possible reasons:
- the machine on which the application was running was CPU bound causing some processes to be swapped out
- there are two mutex locks within the StackTrace_entry call that is used to output the "publishMessage" and "publish" entries in the trace, one for the StackTrace call, one for the Log to which the messages are written.  These shouldn't take effect unless more than one thread was being used, and even then a wait for 20 seconds seems unlikely to occur.

**Comment by kamilgucwa** [comment]
Thank you for your response. The first case is more likely to occur. 

Looking further into logs I've found, that there are more places where the timestamp jumps significantly (see attached log file [paho.20170705_1911-1913.txt](https://github.com/eclipse/paho.mqtt.c/files/1138421/paho.20170705_1911-1913.txt), lines: 4-mentioned above, 544, 584, 864). Later on, the process falls into looks-like-infinite loop of such sequence:

```
20170705 191304.555 (1662473696)   (2)> MQTTClient_yield_sleepParam:1808
20170705 191304.555 (1662473696)    (3)> MQTTClient_cycle:1545
20170705 191304.555 (1662473696)     (4)> Socket_getReadySocket:217
20170705 191304.555 Return code 0 from read select
20170705 191304.555 (1662473696)      (5)> Socket_continueWrites:776
20170705 191304.555 (1662473696)      (5)< Socket_continueWrites:798 (0)
20170705 191304.555 Return code 1 from write select
20170705 191304.555 (1662473696)      (5)> isReady:193
20170705 191304.555 (1662473696)      (5)< isReady:198 (0)
20170705 191304.555 (1662473696)     (4)< Socket_getReadySocket:283 (0)
20170705 191304.555 (1662473696)     (4)> MQTTClient_retry:1525
20170705 191304.555 (1662473696)      (5)> MQTTProtocol_retry:629
20170705 191304.555 (1662473696)      (5)< MQTTProtocol_retry:648
20170705 191304.555 (1662473696)     (4)< MQTTClient_retry:1535
20170705 191304.555 (1662473696)    (3)< MQTTClient_cycle:1615 (0)
20170705 191304.555 (1662473696)   (2)< MQTTClient_yield_sleepParam:1830
```
Note: void MQTTClient_yield_sleepParam(int timeoutInMilliseconds) is a copy of void MQTTClient_yield(void) which we call with 1ms timeout during MQTTClient_publish.

That was the last week case. Today the process throw such a core:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x00007f5b4663e735 in SSL_write () from /opt/isp/rel16/lib/extern/libssl.so.1.0.0
(gdb) bt
#0 0x00007f5b4663e735 in SSL_write () from /opt/isp/rel16/lib/extern/libssl.so.1.0.0
#1 0x00007f5b40a7caee in SSLSocket_continueWrite (pw=pw@entry=0x900194) at src/SSLSocket.c:823
#2 0x00007f5b40a7e8a1 in Socket_continueWrite (socket=socket@entry=14) at src/Socket.c:719
#3 0x00007f5b40a7ea5f in Socket_continueWrites (pwset=pwset@entry=0x7ffd80a69830) at src/Socket.c:780
#4 0x00007f5b40a7ec85 in Socket_getReadySocket (more_work=more_work@entry=0, tp=tp@entry=0x7ffd80a698d0) at src/Socket.c:247
#5 0x00007f5b40a8060d in MQTTClient_cycle (sock=sock@entry=0x7ffd80a6991c, timeout=1, rc=rc@entry=0x7ffd80a69918) at src/MQTTClient.c:1558
#6 0x00007f5b40a8235e in MQTTClient_yield_sleepParam (timeoutInMilliseconds=timeoutInMilliseconds@entry=1) at src/MQTTClient.c:1819
#7 0x00007f5b40a825d1 in MQTTClient_publish (handle=handle@entry=0x8d6934,
topicName=topicName@entry=0x92d588 "/toTester/m037ist38499784/testgroupdata/condensed-testgroupdata-delivery", payloadlen=810858, payload=0xb3f628, qos=1,
retained=0, deliveryToken=deliveryToken@entry=0x7ffd80a69b18) at src/MQTTClient.c:1467
#8 0x00007f5b40a8270b in MQTTClient_publishMessage (handle=0x8d6934, topicName=0x92d588 "/toTester/m037ist38499784/testgroupdata/condensed-testgroupdata-delivery",
message=0x7ffd80a69aa0, deliveryToken=0x7ffd80a69b18) at src/MQTTClient.c:1513
```
Unfortunately, paho logging was turned off this week. 

It seems, that both cases can be connected with SSL.

**Comment by icraggs** [comment]
So the conclusion is that the delay lies within OpenSSL?  If so, can we close this issue?

**Comment by kamilgucwa** [comment]
We have turned paho logging on again, turning SSL off. We will see if that will prevent from hangs. For now, we can close this issue.
