### ISSUE TITLE
Mutex release in MQTTAsync_receiveThread is dangerous

### ISSUE THREAD

**Issue by CallumAttryde** [eclipse-paho/paho.mqtt.c#523]
We think we have found a crash but due to the explicit unlocking wanted to verify. A regular in-house test (create a sender and two receiver clients connected via a broker, kill the broker then restart to ensure everything reconnects) surfaced a crash stemming from this section of code (begins at MQTTAsync.c:2029 at time of writing 336f027):

```
if (m->c->connected == 1)
{
    MQTTAsync_unlock_mutex(mqttasync_mutex);
    MQTTAsync_disconnect_internal(m, 0);
    MQTTAsync_lock_mutex(mqttasync_mutex);
}
```

```
...
[New LWP 32347]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/apama_build/br/rel/10.3.0.x/apama-src/output-amd64-rhel7-release/SoftwareAG/Ap'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f84bf7c6c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#0  0x00007f84bf7c6c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f84bf7ca028 in __GI_abort () at abort.c:89
#2  0x00007f84c370d76d in com::apama::coreHandler(int, siginfo_t*, void*) () from /apama_build/br/rel/10.3.0.x/apama-src/output-amd64-rhel7-release/SoftwareAG/Apama/lib/libapclient.so.10.3
#3  <signal handler called>
#4  ListInsert (aList=0x7f84a4372284, content=content@entry=0x7f8484001034, size=size@entry=8, index=0x7f847c062e54) at src/LinkedList.c:122
#5  0x00007f84bd9518cc in MQTTAsync_addCommand (command=0x7f8484001034, command_size=command_size@entry=8) at src/MQTTAsync.c:895
#6  0x00007f84bd951d67 in MQTTAsync_disconnect1 (handle=handle@entry=0x7f84a4372354, options=options@entry=0x7f847b1e2218, internal=internal@entry=1) at src/MQTTAsync.c:2551
#7  0x00007f84bd951dc7 in MQTTAsync_disconnect_internal (handle=handle@entry=0x7f84a4372354, timeout=0) at src/MQTTAsync.c:2564
#8  0x00007f84bd952891 in MQTTAsync_receiveThread (n=<optimised out>) at src/MQTTAsync.c:1845
#9  0x00007f84bfb5d184 in start_thread (arg=0x7f847b1e4700) at pthread_create.c:312
#10 0x00007f84bf88a37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 27 (Thread 0x7f847a1e2700 (LWP 32347)):
#0  0x00007f84bfb607de in __pthread_mutex_unlock_usercnt (decr=1, mutex=mutex@entry=0x7f84bdbfb180 <log_mutex_store>) at pthread_mutex_unlock.c:57
#1  __GI___pthread_mutex_unlock (mutex=mutex@entry=0x7f84bdbfb180 <log_mutex_store>) at pthread_mutex_unlock.c:310
#2  0x00007f84bd958c9c in Thread_unlock_mutex (mutex=mutex@entry=0x7f84bdbfb180 <log_mutex_store>) at src/Thread.c:142
#3  0x00007f84bd95a967 in Log_stackTrace (log_level=log_level@entry=TRACE_MINIMUM, msgno=msgno@entry=9, thread_id=<optimised out>, current_depth=<optimised out>, name=name@entry=0x7f84bd95db10 <__func__.22478> "MQTTAsync_sendMessage", line=line@entry=2867, rc=rc@entry=0x0) at src/Log.c:450
#4  0x00007f84bd955e05 in StackTrace_entry (name=name@entry=0x7f84bd95db10 <__func__.22478> "MQTTAsync_sendMessage", line=line@entry=2867, trace_level=trace_level@entry=TRACE_MINIMUM) at src/StackTrace.c:110
#5  0x00007f84bd955042 in MQTTAsync_sendMessage (handle=0x7f84a4372354, destinationName=0x7f84a4002158 "test", message=0x7f847a1de130, response=0x7f847a1de160) at src/MQTTAsync.c:2867
...
// redacted user stack
...
#21 0x00007f84bfb5d184 in start_thread (arg=0x7f847a1e2700) at pthread_create.c:312
#22 0x00007f84bf88a37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 26 (Thread 0x7f847b9e5700 (LWP 32344)):
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f84bfb5f649 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f84bfb5f470 in __GI___pthread_mutex_lock (mutex=0x7f84bdb649c0 <stack_mutex_store>) at ../nptl/pthread_mutex_lock.c:79
#3  0x00007f84bd958c97 in Thread_lock_mutex (mutex=mutex@entry=0x7f84bdb649c0 <stack_mutex_store>) at src/Thread.c:118
#4  0x00007f84bd955e95 in StackTrace_exit (name=name@entry=0x7f84bd95de60 <__func__.22179> "MQTTAsync_removeResponsesAndCommands", line=line@entry=1685, rc=rc@entry=0x0, trace_level=trace_level@entry=TRACE_MINIMUM) at src/StackTrace.c:124
#5  0x00007f84bd95143e in MQTTAsync_removeResponsesAndCommands (m=0x7f84a4372354) at src/MQTTAsync.c:1685
#6  0x00007f84bd9516a1 in MQTTAsync_cleanSession (client=client@entry=0x7f84a43727a4) at src/MQTTAsync.c:2180
#7  0x00007f84bd95170e in MQTTAsync_closeSession (client=0x7f84a43727a4) at src/MQTTAsync.c:2144
#8  0x00007f84bd951fbe in MQTTAsync_checkDisconnect (handle=0x7f84a4372354, command=command@entry=0x7f84880be5d4) at src/MQTTAsync.c:985
#9  0x00007f84bd9544ec in MQTTAsync_processCommand () at src/MQTTAsync.c:1362
#10 MQTTAsync_sendThread (n=<optimised out>) at src/MQTTAsync.c:1575
#11 0x00007f84bfb5d184 in start_thread (arg=0x7f847b9e5700) at pthread_create.c:312
#12 0x00007f84bf88a37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
...
```

As shown in the attached back trace, this code reaches ``MQTTAsync_discconect1`` which starts interacting with the ``commands`` queue (via ``MQTTAsync_addCommand``), which is protected by the ``mqttcommand_mutex``. However, releasing `mqttasync_mutex` allows for a different thread to process the next command, which if it is a DISCONNECT command (potentially just added by the other thread?) reaches ``MQTTAsync_removeResponsesAndCommands``, which mutates the ``commands`` queue with no ``mqttcommand_mutex`` held, thus potentially at the same time as the other thread and so UD. 

For our purposes, removing this fiddling with the mutex at the section described above fixed the issue and has not appeared to introduce any deadlocks (tested ~60 times every day on several different platforms for the past year). Performance impact not investigated.

**Comment by icraggs** [comment]
Yes, that looks correct.  Thanks!
