### ISSUE TITLE
Segfault in MQTTProtocol_emptyMessageList

### ISSUE THREAD

**Issue by JGrossholtz** [eclipse-paho/paho.mqtt.c#583]
Hello,

I got a Segmentation fault while stopping the paho MQTT client using version 3.1.0 after I called MQTTAsync_destroy ( from a separated thread this time).

I am running some stress tests where I create and destroy instances of my code and the paho mqtt client. It does not try to publish or subscribe to anything. So this may not be a "normal" usage. Anyway I have been able to reproduce this three time now.

**Here is the stacktrace:**
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4abbaec48b in MQTTProtocol_emptyMessageList (msgList=0x7f4aa0003494)
    at /paho.mqtt.c-1.3.0/src/MQTTProtocolClient.c:812
812			Messages* m = (Messages*)(current->content);
[Current thread is 1 (Thread 0x7f49ecf89700 (LWP 8224))]
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/local/ssl/lib/libeo.so.1.17.2-gdb.py", line 7, in <module>
    import eo_gdb
ImportError: No module named 'eo_gdb'
(gdb) set debug-file-directory /home/builder/src/host/libcommon/
(gdb) set debug-file-directory /usr/local/lib/
[...]
(gdb) bt full
#0  0x00007f4abbaec48b in MQTTProtocol_emptyMessageList (msgList=0x7f4aa0003494)
    at /paho.mqtt.c-1.3.0/src/MQTTProtocolClient.c:812
        m = 0xbbafe5f0
        current = 0x7f4a
        __func__ = "MQTTProtocol_emptyMessageList"
#1  0x00007f4abbae691b in MQTTAsync_cleanSession (client=0x7f4aa0003254) at /paho.mqtt.c-1.3.0/src/MQTTAsync.c:2620
        rc = 0
        found = 0x0
        __func__ = "MQTTAsync_cleanSession"
#2  0x00007f4abbae6885 in MQTTAsync_closeSession (client=0x7f4aa0003254, reasonCode=MQTTREASONCODE_SUCCESS, props=0x0)
    at /paho.mqtt.c-1.3.0/src/MQTTAsync.c:2592
        __func__ = "MQTTAsync_closeSession"
#3  0x00007f4abbae49a7 in MQTTAsync_destroy (handle=0x559d4558ca48 <g_mqtt_client+8>)
    at /paho.mqtt.c-1.3.0/src/MQTTAsync.c:1943
        m = 0x7f4aa0002f44
        __func__ = "MQTTAsync_destroy"
#4  0x0000559d45380321 in remote_deinit_client () at src/remote.c:751
        retval = 0
        ret = 32585
        i = 1
        __FUNCTION__ = "remote_deinit_client"
#5  0x0000559d45379378 in test12_event_unable_to_connect () at remote_test.c:841
        ret = 0
        __FUNCTION__ = "test12_event_unable_to_connect"
#6  0x0000559d4537e732 in _thread_paho_connection_events (thread=0x559d45595080 <g_mqtt_client+34368>) at src/remote.c:287
        ret = 0
        __FUNCTION__ = "_thread_paho_connection_events"
#7  0x0000559d453810a7 in _thread (data=0x559d45595080 <g_mqtt_client+34368>) at src/thread.c:37
        thread = 0x559d45595080 <g_mqtt_client+34368>
        ret = 0
        name = "libpaho events\000"
        __FUNCTION__ = "_thread"
#8  0x00007f4abb680494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#9  0x00007f4abb3c2acf in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.


```

**Comment by icraggs** [comment]
Some trace please?  Destroy is the most 'dangerous' call as it removes all the data structures.  If it's called while there is still some activity for the client, things will go wrong.  If you call disconnect with a 0 timeout, it's quite likely that activity will not have completely finished.

**Comment by icraggs** [comment]
Would need client lib trace as described in the readme.
